name: Delete Resource
about: Use this template to request to delete resources.

body:
  - type: textarea
    id: resource
    attributes:
      label: What would you like to be deleted?
    validations:
      required: true

  - type: textarea
    id: category
    attributes:
      label: On which page is this deletion is required?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Why you want to have this deleted?
    validations:
      required: true